vec3 main(in vec2 Origin, in vec2 UV, in vec Size, in vec3 Color, in vec3 multicolor, inout vec3 testout, inout vec3 test2) {

    vec3 CircleMask = vec3(0.,0.,0.);

    if (length((Origin - UV)) < Size)
    {
        CircleMask = vec3(1.,1.,1.);
    }

    testout = vec3(0.64, 0.42, 0.12);
    test2 = vec3(0.2, 0.11, 0.00);
    return CircleMask * test();
    //return vec3(0.64, 0.42, 0.12);
}

vec3 test() {
    return Color;
}
